apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth-chart.name" . }}
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
